uploads = []
outputs = []

[[generated]]
id = "8ToHxyDGZnDnoTa5B2W5-"
uri = "file://public/media/services/service-chargeuse.png"
type = "image"
title = "chargeuse loading construction site"

[[generated]]
id = "JwMBINxiJe28AOsgUcMVS"
uri = "file://public/media/services/service-pelle.png"
type = "image"
title = "excavator digging trench"

[[generated]]
id = "bY8z7JBT5ppi5XtgCX5jz"
uri = "file://public/media/services/service-chauffeur.png"
type = "image"
title = "operator inside heavy equipment cabin"

[[generated]]
id = "XoUzfaDJtZVu0tj6sJ9IN"
uri = "file://public/media/services/service-maintenance.png"
type = "image"
title = "mechanic maintaining heavy equipment"

[[generated]]
id = "uSnodAmBfGPhVTJBu0_rO"
uri = "file://public/media/brands/cat-logo.png"
type = "image"
title = "CAT Caterpillar logo"

[[generated]]
id = "BGrprGA1B_XvQ4JJskQ6R"
uri = "file://public/media/brands/sany-logo.png"
type = "image"
title = "SANY logo"

[[generated]]
id = "m-tjQAjt8qdI9x8baYntc"
uri = "file://public/media/brands/shantui-logo.png"
type = "image"
title = "Shantui logo"

[[generated]]
id = "wByDie0rPD_XKuMcOnON3"
uri = "file://public/media/brands/sem-logo.png"
type = "image"
title = "SEM logo"

[[generated]]
id = "MD-ehVZzDaf9oWHSmjsCo"
uri = "file://public/media/brands/saptrans-logo.png"
type = "image"
title = "Saptrans logo Cameroun"
